# Generated by Django 4.2.1 on 2023-06-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('block_user', 'can block users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
