# Generated by Django 4.2.1 on 2023-06-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='client_email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_signed_up',
            field=models.BooleanField(default=True, verbose_name='is_signed_up'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='client_name'),
        ),
    ]
