# Generated by Django 4.2.1 on 2023-06-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.CharField(max_length=100, verbose_name='newsletter_name')),
                ('start_campaign', models.DateTimeField(verbose_name='from')),
                ('finish_campaign', models.DateTimeField(verbose_name='until')),
                ('status', models.CharField(choices=[('created', 'Created'), ('launched', 'Launched'), ('finished', 'Finished')], default='created', max_length=10, verbose_name='newsletter_status')),
                ('regularity', models.CharField(choices=[('daily', 'Daily'), ('daily', 'Weekly'), ('daily', 'Monthly')], max_length=10, verbose_name='newsletter_regularity')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='NewsletterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_subject', models.CharField(max_length=100, verbose_name='newsletter_subject')),
                ('newsletter_content', models.TextField(verbose_name='newsletter_content')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newslettersettings')),
            ],
            options={
                'verbose_name': 'Newsletter Content',
                'verbose_name_plural': 'Newsletter Content',
            },
        ),
        migrations.CreateModel(
            name='NewsletterAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(blank=True, null=True, verbose_name='last_attempt')),
                ('attempt_status', models.CharField(blank=True, choices=[('success', 'success'), ('failure', 'failure'), ('in_progress', 'in_progress')], max_length=12, null=True, verbose_name='attempt_status')),
                ('email_server_response', models.TextField(blank=True, null=True, verbose_name='email_server_response')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newslettersettings', verbose_name='newsletter')),
            ],
            options={
                'verbose_name': 'Newsletter Attempt',
                'verbose_name_plural': 'Newsletter Attempts',
            },
        ),
    ]
