# Generated by Django 4.2.1 on 2023-06-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newsletterattempts_attempt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersettings',
            name='newsletter_content',
            field=models.TextField(blank=True, null=True, verbose_name='newsletter_content'),
        ),
        migrations.AddField(
            model_name='newslettersettings',
            name='newsletter_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='newsletter_subject'),
        ),
        migrations.DeleteModel(
            name='NewsletterContent',
        ),
    ]
