# Generated by Django 4.2.1 on 2023-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_alter_newslettersettings_newsletter_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersettings',
            name='newsletter_content',
        ),
        migrations.RemoveField(
            model_name='newslettersettings',
            name='newsletter_subject',
        ),
        migrations.AddField(
            model_name='newslettersettings',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='newslettersettings',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='subject'),
        ),
    ]
