# Generated by Django 4.2.1 on 2023-06-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_remove_newslettersettings_newsletter_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersettings',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='newslettersettings',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='subject'),
        ),
    ]
