# Generated by Django 4.2.1 on 2023-06-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_rename_newslettersettings_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='slug'),
        ),
    ]
