# Generated by Django 4.2.1 on 2023-06-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_newsletter_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=100, unique=True, verbose_name='subject'),
        ),
    ]
