# Generated by Django 4.2.1 on 2023-06-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_newsletter_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, verbose_name='slug'),
        ),
    ]
