# Generated by Django 4.2.1 on 2023-06-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_newsletter_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
    ]
