# Generated by Django 4.2.1 on 2023-06-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_alter_newsletter_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterattempts',
            name='attempt_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], max_length=12, null=True, verbose_name='attempt_status'),
        ),
    ]
