# Generated by Django 4.2.1 on 2023-06-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_alter_newsletterattempts_attempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterattempts',
            name='email_server_response',
        ),
        migrations.CreateModel(
            name='EmailServerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='recipient_email')),
                ('response', models.TextField(blank=True, null=True, verbose_name='email_server_response')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletterattempts', verbose_name='newsletter_attempt')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
