# Generated by Django 4.2.1 on 2023-06-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_newsletterattempts_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailserverresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_response', to='newsletter.newsletterattempts', verbose_name='newsletter_attempt'),
        ),
    ]
