# Generated by Django 4.2.1 on 2023-06-18 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0017_alter_emailserverresponse_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='newsletter_user'),
        ),
    ]
