# Generated by Django 4.2.1 on 2023-06-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0018_newsletter_newsletter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterattempts',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_attempt', to='newsletter.newsletter', verbose_name='newsletter'),
        ),
    ]
