# Generated by Django 4.2.1 on 2023-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_alter_newsletterattempts_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterattempts',
            name='attempt_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], default='failure', max_length=12, null=True, verbose_name='attempt_status'),
        ),
    ]
