# Generated by Django 4.2.1 on 2023-06-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0020_alter_newsletterattempts_attempt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterattempts',
            name='attempt_status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('in_progress', 'In_progress')], default='in_progress', max_length=12, null=True, verbose_name='attempt_status'),
        ),
    ]
