# Generated by Django 4.2.1 on 2023-07-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0022_alter_newsletter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_name', models.CharField(max_length=100, unique=True, verbose_name='mode_name')),
                ('mode_settings', models.CharField(max_length=250, verbose_name='mode_settings')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='regularity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.schedule', verbose_name='regularity_settings'),
        ),
    ]
