# Generated by Django 4.2.1 on 2023-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_client_user'),
        ('newsletter', '0023_schedule_alter_newsletter_regularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_clients',
            field=models.ManyToManyField(related_name='client_newsletters', to='client.client'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter',
            field=models.CharField(max_length=100, verbose_name='newsletter_title'),
        ),
    ]
