# Generated by Django 4.2.1 on 2023-10-30 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsletter', '0025_newsletter_newsletter_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_newsletters', to=settings.AUTH_USER_MODEL, verbose_name='newsletter_user'),
        ),
    ]
