# Generated by Django 4.2.1 on 2023-10-30 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0026_alter_newsletter_newsletter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='newsletter_clients',
        ),
    ]
