# Generated by Django 4.2.1 on 2023-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='blog_title')),
                ('content', models.TextField(verbose_name='blog_content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_image/', verbose_name='blog_image')),
                ('views', models.IntegerField(default=0, verbose_name='blog_views')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='blog_created')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
